### ISSUE TITLE
Implement Search Functionality

### ISSUE THREAD

**Issue by bhamodi** [optimizely/developers.optimizely.com#156]
Adding this feature request here. It would be great to have a search bar that allows users to quickly search for content/keywords in our documentation. FYI: @tscanlin @mmoravec

**Comment by tscanlin** [comment]
+1 Would love to see this and we had discussed it way back when.. Unfortunately I don't currently have the bandwidth.

Although I did something similar for the new design.optimizely.com which is currently in progress.

**Comment by bhamodi** [comment]
Oh nice! How did you do it for design.optimizely.com? I could try to replicate a similar approach in this repo.

**Comment by tscanlin** [comment]
Well it helped that there was already a json file that had all the content for the site in it, see: https://github.com/optimizely/design-dot/blob/master/assets/js/search.js

We would probably need to do that.. In the markdown gulp task we would need to store the json coming from 'gulp-markdown-to-json' see this line: https://github.com/optimizely/developers.optimizely.com/blob/master/gulp/tasks/markdown.js#L43

I don't expect you to do this btw, but wanted to share this here for future reference in case we decide to do it.

**Comment by tscanlin** [comment]
This is done!

**Comment by bhamodi** [comment]
Nice. :)
