### ISSUE TITLE
Upgrade to new lego version.

### ISSUE THREAD

**Issue by bhamodi** [optimizely/developers.optimizely.com#174]
@tscanlin - We just released a much more polished version of [lego.](https://github.com/optimizely/lego) There are a few breaking changes, so we can't just update the `package.json` file, but it would be cool to upgrade for all the new UI styles. This issue will track any progress made on upgrading the version of lego used in this repo.

**Comment by bhamodi** [comment]
@danoc - is there anywhere that will show me what needs to be upgraded/changed from version 0.0.1 to version 6.0.0? Obviously there are a lot of breaking changes that make this task quite difficult.

**Comment by tscanlin** [comment]
This shouldn't be too bad, I planned to actually try tackling this next week. Thanks for making the task to track it though.

**Comment by tscanlin** [comment]
Oh, and there is the changelog: https://github.com/optimizely/oui/blob/master/CHANGELOG.md
@bhamodi ^
:)

**Comment by bhamodi** [comment]
Sweet, I'll this task for you @tscanlin! :)

**Comment by danoc** [comment]
@bhamodi – For reference, this is the changelog. (It's not a perfect guide though.)
https://github.com/optimizely/oui/blob/master/CHANGELOG.md

@tscanlin – Post in `#oui` when it's on the latest version and I'll update the doc that I use to track projects using OUI.

**Comment by tscanlin** [comment]
I'm gonna close this issues since I have an open PR tracking this now.
https://github.com/optimizely/developers.optimizely.com/pull/224

Thanks!
