### ISSUE TITLE
When linking to other anchors on the same page, we should specify the anchor but not the path

### ISSUE THREAD

**Issue by nchilada** [optimizely/developers.optimizely.com#257]
When linking from e.g. [/rest/customer-profiles/#customer_profiles](http://developers.optimizely.com/rest/customer-profiles/#customer_profiles) to [/rest/customer-profiles/#alias](http://developers.optimizely.com/rest/customer-profiles/#alias), the link href should be `#alias` rather than `/rest/customer-profiles/#alias` or `http://developers.optimizely.com/rest/customer-profiles/#alias`.

What's wrong with hardcoding the path, as we do now?
* If a visitor on [/rest/customer-profiles/index.html#customer_profiles](http://developers.optimizely.com/rest/customer-profiles/index.html#customer_profiles) or [/rest/customer-profiles/#customer_profiles](http://developers.optimizely.com/rest/customer-profiles/#customer_profiles) tries to jump to [/rest/customer-profiles#alias](http://developers.optimizely.com/rest/customer-profiles#alias) (with no trailing slash), they will have to load a new page.  This takes time and results in a suboptimal experience.
* Links break if a path changes from e.g. [/rest/customer-profiles/](http://developers.optimizely.com/rest/customer-profiles) to [/rest/uploaded-profiles/](http://developers.optimizely.com/rest/uploaded-profiles).

**Comment by tscanlin** [comment]
Makes sense to me. Probably not too urgent but a good idea / guideline when updating content.

**Comment by nchilada** [comment]
Cool, thanks!  We can indeed leave this on the back burner for now.
