### ISSUE TITLE
Make it easy to set up redirects from one URL in the dev docs to another

### ISSUE THREAD

**Issue by nchilada** [optimizely/developers.optimizely.com#258]
Whenever we reorganize our documentation (as in [PR 256](https://github.com/optimizely/developers.optimizely.com/pull/256)), we run the risk of breaking links from other websites and bookmarks.  As a documentation writer, I'd love a barebones, declarative config schema for creating appropriate redirects.

Server-side would be ideal, but is probably unfeasible since the docs are serves as static content.  Client-side redirects would suffice; they'd probably need to be implemented using JavaScript on the HTTP 404 page and on every other page as well.

**Comment by tscanlin** [comment]
Closing, since this is done in a PR. We can discuss in #346

**Comment by nchilada** [comment]
Thanks @tscanlin!
