### ISSUE TITLE
Add Travis CI integration

### ISSUE THREAD

**Issue by danoc** [optimizely/developers.optimizely.com#279]
I set it up for OUI and have it check for lint issues and compile the SCSS (solid sanity check) on every PR. You can also have it deploy to GH pages every time a PR is merged: https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db#.r31rjyaj2

cc: @tscanlin

**Comment by tscanlin** [comment]
That's awesome, thanks @danoc! So Travis can run node scripts to compile everything?

**Comment by danoc** [comment]
@tscanlin Yes! It's really slick.

**Comment by tscanlin** [comment]
Hey @danoc do you know how to get "Personal Access Tokens " that aren't tied to a specific user? It would be great to set this up in a way that isn't tied to my personal github account if possible.

No worries if you don't know.

**Comment by danoc** [comment]
@tscanlin Not super sure. Which tokens are you referring to?

**Comment by tscanlin** [comment]
They are called "Personal Access Tokens " in the article you sent.. but I'll ask Sonesh and see if we can generate Organizational ones.

Thanks
