### ISSUE TITLE
New navigation layout

### ISSUE THREAD

**Issue by tscanlin** [optimizely/developers.optimizely.com#343]
Hey @mauerbac & @jprovine,

This is what I'm thinking so far for the new navigation layout. What do you think?

![screen shot 2016-05-05 at 3 31 02 pm](https://cloud.githubusercontent.com/assets/5033032/15059357/f77bbd08-12d6-11e6-8bd6-e7d69db6a82b.png)

![screen shot 2016-05-05 at 3 34 39 pm](https://cloud.githubusercontent.com/assets/5033032/15059356/f7793e48-12d6-11e6-86f1-a180bb0b282e.png)

**Comment by mauerbac** [comment]
wow, @tscanlin!! Super fast turn around :) This looks great and is exactly what I had in mind. If you start the PR, I should be able to help with tweaking the content, etc... I'll create & update a JIRA ticket later today.

**Comment by tscanlin** [comment]
Well, it's fake.. Haha. :)

I just wanted to start with HTML only and get the style nailed down. I still need to think how to do subpages for these top level pages (probably just indented a bit). REST API is an easier one because it is all just one page.

Anyway, I will work on that and getting it all hooked up in the code.

**Comment by tscanlin** [comment]
Closing, since this is done in a PR. We can discuss in #346
